name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 0
      DEBUG: 1
      RELEASE: 0
      ENV: Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install Dependencies
        run: |
          chmod +x ./init_deps.sh
          ./init_deps.sh


      # - name: Install agbcc
      #   run: |
      #      ./build.sh
      #      ./install.sh ../
      #   working-directory: agbcc

      #- name: Agbcc
      #  env:
      #    MODERN: 0
      #    COMPARE: 0
      #  run: make -j${nproc} -O all

      # - name: Build Debug
      #   env:
      #     MODERN: 1
      #     COMPARE: 0
      #     RELEASE: 0
      #   run: make -j${nproc} -O -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function all
      #   # -Wno-unused-but-set-variable is to silence the warnings of the unused variables, useful when trying to compile with my mods
        
      - name: Set Environment Variables for Specific Branches
        if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/prod'
        run: |
          echo "DEBUG=0" >> $GITHUB_ENV
          echo "RELEASE=1" >> $GITHUB_ENV
          echo "ENV=Release" >> $GITHUB_ENV

      - name: Display Environment Variables
        run: |
          echo "DEBUG=$DEBUG"
          echo "RELEASE=$RELEASE"
          echo "ENV=$ENV"

      - name: Build-${{ env.ENV }}
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function all
        # -Wno-unused-but-set-variable is to silence the warnings of the unused variables, useful when trying to compile with my mods

      - uses: actions/upload-artifact@v4
        with:
            name: emeraldrogue
            path: emeraldrogue.gba
            retention-days: 1
  
      - uses: actions/upload-artifact@v4
        with:
            name: emeraldrogue_elf
            path: emeraldrogue.elf
            retention-days: 1
            
      - uses: actions/upload-artifact@v4
        with:
            name: emeraldrogue_map
            path: emeraldrogue.map
            retention-days: 1

            ## what's below can be removed if ever build from github again
            ## some tests fail anyway, can't be bother to fix these so fuck off
      # - name: Update Memory Stats
      #   uses: actions/upload-artifact@v3
      #   with:
      #         name: Memory Stats
      #         path: emeraldrogue_memorystats.csv
      #         retention-days: 1
    
      # - name: Test
      #   env:
      #       MODERN: 1
      #       TEST: 1
      #   run: |
      #       make -j${nproc} -O emeraldrogue-test.elf
      #       make -j${nproc} check

